In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
df=pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
#### Independent and Dependent Features
X=df.drop("Class",axis=1)
y=df.Class

In [12]:
x_train, x_test, y_train, y_test=train_test_split(X, y, train_size=0.7)

In [8]:

log_class=LogisticRegression()
grid={'C':10.0**np.arange(-2,3),
     'penalty': ['l1', 'l2']}
cv=KFold(n_splits=5, random_state=None, shuffle=False)

In [16]:
#cross validation Kfold and hyper parameter tuning
#important step in handling imabalnced dataset

clf=GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')



In [19]:
def classification(x_train, x_test, y_train, y_test):
    clf.fit(x_train, y_train)
    y_pred=clf.predict(x_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))

In [20]:
classification(x_train, x_test, y_train, y_test)

/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html

/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85300
           1       0.65      0.62      0.63       143

    accuracy                           1.00     85443
   macro avg       0.83      0.81      0.82     85443
weighted avg       1.00      1.00      1.00     85443

[[85253    47]
 [   55    88]]
0.9988062216916541


/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
class_weight={0:1,1:100}

In [25]:
rfclas=RandomForestClassifier(class_weight=class_weight)
rfclas.fit(x_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [26]:
y_pred=rfclas.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85300
           1       0.93      0.80      0.86       143

    accuracy                           1.00     85443
   macro avg       0.97      0.90      0.93     85443
weighted avg       1.00      1.00      1.00     85443

[[85292     8]
 [   29   114]]
0.9995669627705019


In [28]:
# from collections import counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
x_train_ns, y_train_ns=ns.fit_resample(x_train, y_train)


/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/imblearn/utils/_validation.py:586: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [32]:
y_train_ns.value_counts()

0    436
1    349
Name: Class, dtype: int64

In [33]:
rfclas=RandomForestClassifier()
rfclas.fit(x_train_ns, y_train_ns)
y_pred=rfclas.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.70      0.82     85300
           1       0.01      0.94      0.01       143

    accuracy                           0.70     85443
   macro avg       0.50      0.82      0.42     85443
weighted avg       1.00      0.70      0.82     85443

[[59580 25720]
 [    8   135]]
0.698886977283101


In [38]:
#over sampling

from imblearn.over_sampling import RandomOverSampler
os=RandomOverSampler(0.5)
x_train_os, y_train_os=os.fit_resample(x_train, y_train)

/home/sunit.kapuria/anaconda3/lib/python3.9/site-packages/imblearn/utils/_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [39]:
rfclas.fit(x_train_os, y_train_os)
y_pred=rfclas.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85300
           1       0.93      0.82      0.87       143

    accuracy                           1.00     85443
   macro avg       0.96      0.91      0.93     85443
weighted avg       1.00      1.00      1.00     85443

[[85291     9]
 [   26   117]]
0.9995903701883126


In [40]:
from imblearn.combine import SMOTETomek

In [42]:
smote=SMOTETomek()
x_train_sm, y_train_sm=smote.fit_resample(x_train, y_train)
print(y_train.value_counts())
print(y_train_sm.value_counts())

0    199015
1       349
Name: Class, dtype: int64
0    198234
1    198234
Name: Class, dtype: int64


In [43]:
rfclas.fit(x_train_sm, y_train_sm)
y_pred=rfclas.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

KeyboardInterrupt: 

In [44]:
from imblearn.ensemble import EasyEnsembleClassifier

In [45]:
easy=EasyEnsembleClassifier()

In [46]:
easy.fit(x_train, y_train)

EasyEnsembleClassifier()

In [47]:
y_pred=easy.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85300
           1       0.04      0.94      0.08       143

    accuracy                           0.96     85443
   macro avg       0.52      0.95      0.53     85443
weighted avg       1.00      0.96      0.98     85443

[[82277  3023]
 [    8   135]]
0.9645260583078777
